import { useState } from 'react'
import CreepyScore from './CreepyScore'
import BreachGrid from './BreachGrid'
import Timeline from './Timeline'
import ProfileBox from './ProfileBox'
import ActionPlan from './ActionPlan'
import ThreatIntel from './ThreatIntel'
import PasswordChecker from './PasswordChecker'
import PhishingDetector from './PhishingDetector'
import styles from './ResultsScreen.module.css'

const TOOLS = [
  { id: 'overview',  label: 'Overview' },
  { id: 'threats',   label: 'Threat Intel' },
  { id: 'password',  label: 'Password Analyser' },
  { id: 'phishing',  label: 'Phishing Detector' },
  { id: 'actions',   label: 'Remediation' },
]

export default function ResultsScreen({ email, data, onReset }) {
  const [tab, setTab] = useState('overview')

  return (
    <div className={styles.wrap}>

      {/* Top bar */}
      <div className={styles.topBar}>
        <div className={styles.topBarLeft}>
          <span className={styles.topBarLabel}>Scan complete —</span>
          <span className={styles.topBarEmail}>{email}</span>
        </div>
        <button className={styles.resetBtn} onClick={onReset}>← New scan</button>
      </div>

      {/* Score always visible */}
      <CreepyScore
        score={data.creepyScore}
        label={data.scoreLabel}
        color={data.scoreColor}
        headline={data.headline}
      />

      {/* Tab nav */}
      <div className={styles.tabs}>
        {TOOLS.map(t => (
          <button
            key={t.id}
            className={`${styles.tab} ${tab === t.id ? styles.tabActive : ''}`}
            onClick={() => setTab(t.id)}
          >
            {t.label}
          </button>
        ))}
      </div>

      {/* Tab content */}
      <div className={styles.tabContent}>

        {tab === 'overview' && (
          <div className={styles.section}>
            <div className={styles.sectionHeader}>
              <span className={styles.sectionTitle}>Data breaches detected</span>
              {data.breaches.length > 0 && (
                <span className={styles.sectionCount}>{data.breaches.length} source{data.breaches.length !== 1 ? 's' : ''}</span>
              )}
            </div>
            <BreachGrid breaches={data.breaches} />

            {data.timeline?.length > 0 && (
              <>
                <div className={styles.sectionHeader} style={{ marginTop: 28 }}>
                  <span className={styles.sectionTitle}>Breach timeline</span>
                  <span className={styles.sectionCount}>your exposure history — click events to expand</span>
                </div>
                <Timeline events={data.timeline} />
              </>
            )}

            <div className={styles.divider} />

            <div className={styles.sectionHeader}>
              <span className={styles.sectionTitle}>AI-inferred profile</span>
              <span className={styles.sectionCount}>generated by Claude in real time</span>
            </div>
            <ProfileBox
              email={email}
              breaches={data.breaches}
              creepyScore={data.creepyScore}
              fallbackProfile={data.profile}
            />
          </div>
        )}

        {tab === 'threats' && (
          <div className={styles.section}>
            <div className={styles.sectionHeader}>
              <span className={styles.sectionTitle}>Dark web threat intelligence</span>
              <span className={styles.sectionCount}>AI-powered · generated by Claude</span>
            </div>
            <ThreatIntel email={email} breaches={data.breaches} />
          </div>
        )}

        {tab === 'password' && (
          <div className={styles.section}>
            <div className={styles.sectionHeader}>
              <span className={styles.sectionTitle}>AI password strength analyser</span>
              <span className={styles.sectionCount}>powered by Claude — nothing is stored</span>
            </div>
            <div className={styles.toolNote}>
              Check if passwords associated with your breached accounts are strong enough.
              Passwords are analysed locally and never transmitted to third parties.
            </div>
            <PasswordChecker />
          </div>
        )}

        {tab === 'phishing' && (
          <div className={styles.section}>
            <div className={styles.sectionHeader}>
              <span className={styles.sectionTitle}>AI phishing URL detector</span>
              <span className={styles.sectionCount}>powered by Claude</span>
            </div>
            <div className={styles.toolNote}>
              Paste any suspicious link to have Claude analyse it for phishing indicators,
              typosquatting, and social engineering techniques.
            </div>
            <PhishingDetector />
          </div>
        )}

        {tab === 'actions' && (
          <div className={styles.section}>
            <div className={styles.sectionHeader}>
              <span className={styles.sectionTitle}>Personalised remediation plan</span>
              <span className={styles.sectionCount}>{data.actions.length} priority actions</span>
            </div>
            <ActionPlan actions={data.actions} />
          </div>
        )}

      </div>

      <div className={styles.footer}>
        <button className={styles.resetBtn2} onClick={onReset}>← Scan another email</button>
        <div className={styles.footerNote}>Privacy Mirror · AI + Cybersecurity · AMD Slingshot Hackathon</div>
      </div>

    </div>
  )
}
